### ISSUE TITLE
Improve Clarity of README.md

### ISSUE THREAD

**Issue by TerabyteTiger** [12vanblart/CodeBreaker40#5]
**File:** _README.md_
**Request:** Update the readme to be more clear. 

Make sure that someone that isn't familiar with the mechanics of the puzzle is able to read the readme and understand the puzzle and what the code's process of solving the puzzle is.

**Comment by makupi** [comment]
I tried my best with https://github.com/12vanblart/CodeBreaker40/pull/12 to restructure a few parts for improved readability.
